language: node_js

os:
 - linux
 - osx

node_js:
  - 6
  - 7
  - 8
  - node

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm i -g yarn

install:
  - yarn install --frozen-lockfile

script:
    - yarn test --verbose
