environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"

install:
  - ps: "Install-Product node $env:nodejs_version x64"
  - yarn install --frozen-lockfile

test_script:
  - node --version
  - yarn --version
  - yarn test --verbose

build: off
